# Generated by Django 5.0.4 on 2024-07-18 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0006_remove_leaverequest_dureemax_leaverequest_motif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='type_conge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conge.conge'),
        ),
    ]
