# Generated by Django 5.0.4 on 2024-07-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0007_alter_leaverequest_type_conge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='type_de_conge',
            field=models.CharField(choices=[('exceptionnel', 'Exceptionnel'), ('maladie', 'Maladie'), ('repos', 'Repos')], default='repos', max_length=100),
        ),
    ]
