# Generated by Django 5.0.4 on 2024-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0008_alter_conge_type_de_conge'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='traitement',
            field=models.BooleanField(default=False),
        ),
    ]
