# Generated by Django 5.0.4 on 2024-07-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0009_leaverequest_traitement'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(default='En attente', max_length=20),
        ),
    ]
