# Generated by Django 5.0.4 on 2024-07-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conge', '0010_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
    ]
